In [5]:
# Task 3: Create a DataFrame

In [2]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["Chris", "Mansyr", "Eska", "Snanzhar", "GPT"],
    "Age": [23, 40, 15, 20, 2],
    "Score": [100, 74, 91, 83, 95]
})

df

       Name  Age  Score
0     Chris   23    100
1    Mansyr   40     74
2      Eska   15     91
3  Snanzhar   20     83
4       GPT    2     95

In [6]:
# Task 4: Data Exploration

In [3]:
print("First 3 rows:")
display(df.head(3))

print("Describe:")
display(df.describe())

avg_score = df["Score"].mean()
print("Average score:", avg_score)

First 3 rows:

     Name  Age  Score
0   Chris   23    100
1  Mansyr   40     74
2    Eska   15     91

Describe:

           Age       Score
count   5.0000    5.000000
mean   20.0000   88.600000
std    13.7659   10.261579
min     2.0000   74.000000
25%    15.0000   83.000000
50%    20.0000   91.000000
75%    23.0000   95.000000
max    40.0000  100.000000

Average score: 88.6

In [7]:
# Task 5: Data Filtering

In [4]:
print("Age > 20:")
display(df[df["Age"] > 20])

print("Score > 80:")
display(df[df["Score"] > 80])

Age > 20:

     Name  Age  Score
0   Chris   23    100
1  Mansyr   40     74

Score > 80:

       Name  Age  Score
0     Chris   23    100
2      Eska   15     91
3  Snanzhar   20     83
4       GPT    2     95